[build]
  # This is the directory that you are publishing from (relative to root of your repo)
  publish = "build/"
  # This will be your default build command
  command = "bundle exec middleman build"

[[redirects]]
  from = "http://hello-yoga.co.uk/*"
  to = "https://www.hello-yoga.co.uk/:splat"
  status = 301
  force = true
  [redirects.headers]
    Cache-Control = "public, max-age=2592000"

[[redirects]]
  from = "http://www.hello-yoga.co.uk/*"
  to = "https://www.hello-yoga.co.uk/:splat"
  status = 301
  force = true
  [redirects.headers]
    Cache-Control = "public, max-age=2592000"

[[redirects]]
  from = "https://hello-yoga.co.uk/*"
  to = "https://www.hello-yoga.co.uk/:splat"
  status = 301
  force = true
  [redirects.headers]
    Cache-Control = "public, max-age=2592000"

[[headers]]
  for = "/"
  [headers.values]
  Link = '''
  </yoga-people.png>; rel=preload; as=image, \
  </hello-yoga.png>; rel=preload; as=image''' # Headers for H2 Server Push
